/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import java.util.Scanner;

import javax.sound.sampled.SourceDataLine;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("나의 목록 관리 시스템");
        System.out.println("------------------------");

        Scanner scanner = new Scanner(System.in);

        System.out.println("번호? ");
        int no = scanner.nextInt();

        System.out.println("이름? ");
        String name= scanner.next();

        System.out.println("나이? ");
        int age = scanner.nextInt();

        System.out.println("재직중? ");
        boolean working = scanner.nextBoolean();

        System.out.println("성별(남자: M, 여자: W)? ");
        String str = scanner.next();
        char gender = str.charAt(0);

        System.out.println("시력(왼쪽, 오른쪽)");
        float leftEye = scanner.nextFloat();
        float rightEye = scanner.nextFloat();

        System.out.println("--------------------------------");

        System.out.printf("번호 : %d", no);

        System.out.printf("나이 : %d", age);

        System.out.printf("이름 : %s\n", name);

        System.out.printf("재직자 : %b\n", working);

        System.out.printf("성별 - 남자(M), 여자(W) : %c\n", gender);

        System.out.printf("좌측시력 - %f, 우측시력 - %f\n", leftEye, rightEye);
    }
}
