/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import java.util.Scanner;

public class App {

    static final int MAX_SIZE = 3;

    static int[] no = new int[MAX_SIZE];
    static String[] name = new String[MAX_SIZE];
    static String[] email = new String[MAX_SIZE];
    static String[] password = new String[MAX_SIZE];
    static char[] gender = new char[MAX_SIZE];
    static int userId = 0;
    static int length = 0;


    public static void main(String[] args) {

        scanner = new Scanner(System.in);
        //회원정보 등록
        for(int i = 0; i < MAX_SIZE; i++) {

            inputMember(i, userId);
            
            length++;

            if(!promptContinue(scanner)) {
                break;
            }

        }

        printMembers();
    }

    static void printTitle() {
        System.out.println("나의 목록 관리 시스템");
        System.out.println("------------------------");
    }

    static void inputMember(int i) {

        no[i] = userId;
        
        System.out.print("이름? ");
        name[i] = scanner.next();

        System.out.print("이메일? ");
        email[i] = scanner.next();

        System.out.print("암호? ");
        password[i] = scanner.next();

        loop: while (true) {

            System.out.print("성별: ");
            System.out.print("  1. 남자 : ");
            System.out.print("  2. 여자 : ");
            System.out.print(">  ");
            String menuNo = scanner.next();
            scanner.nextLine(); // 다른 메소드에서 작업을 할 때 방해되지 않도록 줄바꿈 코드를 제거함.

            switch (menuNo) {
                case "1":
                    gender[i] = 'M';
                    break loop;
                case "2":
                    gender[i] = 'W';
                    break loop;
                default:
                    System.out.println("무효한 번호입니다.");
            }

        }

        no[i] = userId++;

        System.out.println("------------------------");

    }

    static boolean promptContinue() {

        System.out.print("계속 하시겠습니까?(Y/n)");
        String str = scanner.nextLine(); // next를 실행하고 남아있는 줄바꿈을 제거
        
        if(!str.equalsIgnoreCase("Y") && !str.equals("")) {
            return false;
        } else {
            return true;
        }

    }

    static void printMembers(int length) {

        for(int i = 0; i < length; i++) {
            System.out.println("번호, 이름, 이메일, 성별");
            System.out.println("------------------------");
            System.out.printf("%d, %s, %s, %c\n", no[i], name[i], email[i], gender[i]);
        }

    }
}
